services:
  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dev
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U user -d dev'"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - 5432:5432
    logging:
      driver: none
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - type: bind
        source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
