// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.778
package docs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import . "github.com/gofs-cli/website/internal/ui/components"

func Prereqs() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"flex flex-col gap-y-2\"><h1 class=\"mb-4 text-4xl font-extrabold\">Prerequisites</h1><h2 class=\"mt-2 text-2xl font-extrabold\">Familiarity with Go</h2><p class=\"para\">You should have some experience with Go. There are some good tutorials <a class=\"link\" href=\"https://go.dev/doc/tutorial/getting-started\">here</a> and <a class=\"link\" href=\"https://tour.golang.org/welcome/1\">here</a> which you can use to get started if you are new to Go.</p><h2 class=\"mt-2 text-2xl font-extrabold\">Go toolchain</h2><p class=\"para\"><a class=\"link\" href=\"https://go.dev/dl/\">Download go</a> for your OS and install it. The official instructions are <a class=\"link\" href=\"https://go.dev/doc/install\">here</a>.</p><p class=\"para mt-4\">If you are using Windows, the installer should setup the path for you. Ensure that `go` is on your path, you should be able to type the command below in `terminal` or `cmd/powershell` and see the installed go version.")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Cmdline("go version").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><p class=\"para mt-4\">Once go is installed, you can add the GOPATH to your system path. GOPATH is where go will install any tools installed using `go install`, This is typically your `$HOME/go/bin`, this should be added to your system PATH to allow you to run installed tools.</p><h2 class=\"mt-2 text-2xl font-extrabold\">Gofs cli</h2><p class=\"para\">Once go is installed, you can install the gofs cli by running:")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Cmdline("go get github.com/gofs-cli/gofs").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><h2 class=\"mt-2 text-2xl font-extrabold\">Local Development</h2><p class=\"para\">The following tools are used in the build workflow to improve developer experience:<ul class=\"my-2 max-w-md list-inside list-disc space-y-1\"><li class=\"text-lg text-gray-500 dark:text-gray-400\">Make for example <a class=\"link\" href=\"https://www.gnu.org/software/make/\">GNU Make</a></li><li><a class=\"link\" href=\"https://docs.npmjs.com/downloading-and-installing-node-js-and-npm\">Npm</a></li></ul></p><p class=\"para\">Once these tools are setup and you have initialized a project you can install all required dependencies with:")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Cmdline("make deps").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><h2 class=\"mt-2 text-2xl font-extrabold\">Database</h2><p class=\"para\">To run a local postgres you will need an OCI compliant container runtime such as:<ul class=\"my-2 max-w-md list-inside list-disc space-y-1\"><li><a class=\"link\" href=\"https://www.docker.com\">Docker</a></li><li><a class=\"link\" href=\"https://podman.io\">Podman</a></li></ul></p><p class=\"para\">Once this is setup and you have initialized a project you can start a Postgres instance with:")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = Cmdline("make dbup").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</p><h2 class=\"mt-2 text-2xl font-extrabold\">Deployment</h2><p class=\"para\">Deployment will be specific to your environment. The gofs default template provides a Github Actions workflow, and this documentation provides sample terraform code to deploy into AWS, Azure and GCP. If you want to use this then you will require:<ul class=\"my-2 max-w-md list-inside list-disc space-y-1\"><li><a class=\"link\" href=\"https://github.com/features/actions\">Github Actions</a></li><li><a class=\"link\" href=\"https://www.terraform.io\">Terraform</a></li></ul></p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
