name: Golang CI

on: workflow_dispatch

jobs:
  checkout:
    name: Checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout project
      - uses: actions/setup-node@v4
        name: Install Node.js
        with:
          node-version: "lts/*"
          check-latest: true
      - run: npm i -g tailwindcss@latest
        name: Install Tailwind CSS
      - run: npx tailwindcss -i ./internal/ui/styles.css -o ./internal/server/assets/css/styles.css
        name: Generate Tailwind CSS
      - uses: actions/setup-go@v5
        name: Install Golang
        with:
          go-version-file: "go.mod"
      - run: go install github.com/a-h/templ/cmd/templ@latest
        name: Install Templ
      - run: templ generate
        name: Generate templ files
      - uses: actions/upload-artifact@v4
        name: Upload artifact
        with:
          name: checkout-${{ github.run_id }}
          path: ${{ github.workspace }}/**/*

  lint:
    needs: checkout
    name: Lint
    uses: "./.github/workflows/lint.yml"

  test:
    needs: checkout
    name: Test
    uses: ./.github/workflows/test.yml
