name: Lint

on: workflow_call

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        name: Get Cached Checkout
        with:
          name: checkout-${{ github.run_id }}
      - uses: golangci/golangci-lint-action@v6
        name: Run golangci-lint
        with:
          version: v1.59
